# Generated by Django 3.1.3 on 2021-01-14 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 20, 6, 46, 497232)),
        ),
    ]
