# Generated by Django 3.1.3 on 2021-01-14 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_listing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 20, 8, 2, 180691)),
        ),
    ]
