# Generated by Django 3.1.3 on 2021-01-15 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210114_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 10, 26, 43, 154624)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField()),
                ('content', models.CharField(max_length=128)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
