# Generated by Django 3.1.3 on 2021-01-16 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210116_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 42, 50, 441265)),
        ),
    ]
