# Generated by Django 3.1.3 on 2021-01-16 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210116_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_img',
            new_name='listing_image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 48, 22, 892123)),
        ),
    ]
